In [8]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [9]:
#复制到剪贴板

In [18]:
df = pd.read_clipboard()
df

    Position Programming Language Ratings
0         21                  SAS   0.69%
1         22                  Lua   0.61%
2         23                 Perl   0.57%
3         24              Fortran   0.57%
4         25                COBOL   0.54%
5         26      (Visual) FoxPro   0.49%
6         27                  Ada   0.48%
7         28               Kotlin   0.47%
8         29               Prolog   0.44%
9         30                 Lisp   0.38%
10        31           PowerShell   0.37%
11        32                Julia   0.36%
12        33               PL/SQL   0.34%
13        34                Scala   0.34%
14        35                 Dart   0.34%
15        36                    D   0.30%
16        37                 Logo   0.26%
17        38                  X++   0.25%
18        39                 ABAP   0.25%
19        40           TypeScript   0.24%
20        41                 Bash   0.23%
21        42               Scheme   0.23%
22        43             VBScript   0.21%
23        44              LabVIEW   0.19%
24        45                   F#   0.19%
25        46                  Awk   0.19%
26        47                 PL/I   0.19%
27        48         Transact-SQL   0.18%
28        49                   ML   0.18%
29        50              Haskell   0.17%

In [21]:
#转换成csv文件 在当前目录中创建文件
df.to_csv('df_io.csv',index=False)
!more df_io.csv #直接打开文件

In [22]:
pd.read_csv('df_io.csv')

    Position Programming Language Ratings
0         21                  SAS   0.69%
1         22                  Lua   0.61%
2         23                 Perl   0.57%
3         24              Fortran   0.57%
4         25                COBOL   0.54%
5         26      (Visual) FoxPro   0.49%
6         27                  Ada   0.48%
7         28               Kotlin   0.47%
8         29               Prolog   0.44%
9         30                 Lisp   0.38%
10        31           PowerShell   0.37%
11        32                Julia   0.36%
12        33               PL/SQL   0.34%
13        34                Scala   0.34%
14        35                 Dart   0.34%
15        36                    D   0.30%
16        37                 Logo   0.26%
17        38                  X++   0.25%
18        39                 ABAP   0.25%
19        40           TypeScript   0.24%
20        41                 Bash   0.23%
21        42               Scheme   0.23%
22        43             VBScript   0.21%
23        44              LabVIEW   0.19%
24        45                   F#   0.19%
25        46                  Awk   0.19%
26        47                 PL/I   0.19%
27        48         Transact-SQL   0.18%
28        49                   ML   0.18%
29        50              Haskell   0.17%

In [25]:
#对于json的读写和操作
df_json = df.to_json()
pd.read_json(df_json)# 把json转化成dataFrame

    Position Programming Language Ratings
0         21                  SAS   0.69%
1         22                  Lua   0.61%
2         23                 Perl   0.57%
3         24              Fortran   0.57%
4         25                COBOL   0.54%
5         26      (Visual) FoxPro   0.49%
6         27                  Ada   0.48%
7         28               Kotlin   0.47%
8         29               Prolog   0.44%
9         30                 Lisp   0.38%
10        31           PowerShell   0.37%
11        32                Julia   0.36%
12        33               PL/SQL   0.34%
13        34                Scala   0.34%
14        35                 Dart   0.34%
15        36                    D   0.30%
16        37                 Logo   0.26%
17        38                  X++   0.25%
18        39                 ABAP   0.25%
19        40           TypeScript   0.24%
20        41                 Bash   0.23%
21        42               Scheme   0.23%
22        43             VBScript   0.21%
23        44              LabVIEW   0.19%
24        45                   F#   0.19%
25        46                  Awk   0.19%
26        47                 PL/I   0.19%
27        48         Transact-SQL   0.18%
28        49                   ML   0.18%
29        50              Haskell   0.17%

In [26]:
df.to_html('df_to.html')